### ISSUE TITLE
Fails to upload artwork everytime

### ISSUE THREAD

**Issue by Raventhicc** [maybeclean/musicbee-rich-presence#18]
All my artwork is embedded in the song itself and is not saved anywhere else. Is that the reason?

```
MusicBee v3.4.7805.33439D  (Win10.0), 23 Sep 2021 16:48:

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'discord.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Utils.Discord.GetAssetList()
   at MusicBeePlugin.Plugin.<ProcessArtwork>d__201.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'discord.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

```

**Comment by LloydTheGolden** [comment]
Same issue, all artwork uploads fail, have the artwork embedded too

**Comment by maybeclean** [comment]
> 
> 
> Same issue, all artwork uploads fail, have the artwork embedded too

The majority of albums i listen to have embedded artwork and this works fine for them, you should have a log in `C:\MusicBee-RichPresence\log.txt` that should give you an idea why its failing.


> 
> 
> All my artwork is embedded in the song itself and is not saved anywhere else. Is that the reason?
> 
> ```
> MusicBee v3.4.7805.33439D  (Win10.0), 23 Sep 2021 16:48:
> 
> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'discord.com'
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at Utils.Discord.GetAssetList()
>    at MusicBeePlugin.Plugin.<ProcessArtwork>d__201.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> ---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'discord.com'
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---<---
> ```

According to the error the HttpClient failed to resolve discord.com for some reason, maybe a DNS issue? Not sure but thats unrelated to the plugin.
